# Generated by Django 4.2.6 on 2023-10-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Kolomyia', '0002_dish_name_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_photos/'),
        ),
    ]
