# Generated by Django 4.2.6 on 2023-10-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Kolomyia', '0003_restaurant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='dish_photos/'),
        ),
    ]
