# Generated by Django 4.2.6 on 2023-11-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Kolomyia', '0005_remove_dish_restaurant_id_dish_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Delivery_Kolomyia.restaurant'),
        ),
    ]
