# Generated by Django 4.2.6 on 2023-11-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Kolomyia', '0006_alter_dish_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery_Kolomyia.customer')),
            ],
        ),
    ]
