# Generated by Django 4.2.6 on 2023-11-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Kolomyia', '0007_customertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cart',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery_Kolomyia.customer')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery_Kolomyia.dish')),
            ],
        ),
    ]
