# Generated by Django 4.2.6 on 2023-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_Kolomyia', '0008_remove_customer_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(through='Delivery_Kolomyia.CartItem', to='Delivery_Kolomyia.dish'),
        ),
    ]
